from tkinter import *

def dire_bonjour():
    fenetre_bonjour = Tk()
    fenetre_bonjour.title("Bonjour !")
    fenetre_bonjour.geometry("200x200")
    bonjour = Label(fenetre_bonjour, text="Bonjour !")
    bonjour.pack()
fenetre_principale = Tk()
fenetre_principale.title("TP Manège Parc d'attraction - BTS CIEL")
fenetre_principale.geometry("450x300")
label=Label(fenetre_principale, text="Manege du parc - Force 1 / Force 2", fg="navy", font="18")
label.pack()
label=Label(fenetre_principale, text="Entrez votre âge et votre taille pour savoir à quelle force vous pouvez faire le manège.", wraplength=400, pady=10)
label.pack()
label=Label(fenetre_principale, text="Entrez votre âge : ")
label.pack()
age=Entry(fenetre_principale, width=10)
age.pack(pady=10)
label=Label(fenetre_principale, text="Entrez votre taille en mètres : ")
label.pack()
taille=Entry(fenetre_principale, width=10)
taille.pack(pady=10)
envoyer=Button(fenetre_principale, text="Envoyer", command=dire_bonjour)
envoyer.pack(pady=10)
fenetre_principale.mainloop()